In [1]:
import numpy as np
import tensorflow as tf 

C:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
a = tf.constant(3.0,dtype =  tf.float32)
b = tf.constant(4.0)
total = a + b

In [3]:
print(a)
print(b)
print(total)

Tensor("Const:0", shape=(), dtype=float32)
Tensor("Const_1:0", shape=(), dtype=float32)
Tensor("add:0", shape=(), dtype=float32)


In [4]:
sess = tf.Session()
print(sess.run(total))

7.0


In [5]:
print(sess.run({'total':total,'a,b':(a,b)}))

{'total': 7.0, 'a,b': (3.0, 4.0)}


In [6]:
vec = tf.random_uniform(shape = (3,))
out1 = vec + 1 
out2 = vec + 2
print(sess.run(vec))
print(sess.run(vec))
print(sess.run((out1,out2)))

[0.10420001 0.22718787 0.2799753 ]
[0.9936385  0.0168581  0.16692102]
(array([1.6321394, 1.2926241, 1.0208822], dtype=float32), array([2.6321394, 2.292624 , 2.0208821], dtype=float32))


In [7]:
x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)
z = x + y

In [8]:
print(sess.run(z, feed_dict={x: 3, y: 4.5}))
print(sess.run(z, feed_dict={x: [1, 3], y: [2, 4]}))

7.5
[3. 7.]


In [9]:
r = tf.random_normal([10,3])

In [10]:
print(sess.run(r))

[[ 1.4261411  -0.29009238  0.4853087 ]
 [-2.5988855  -1.7661964  -0.83421594]
 [ 0.3818144  -1.2097613   0.18714468]
 [ 0.31098142 -0.6946326   1.0866145 ]
 [-0.27145576 -1.3658715   2.0566988 ]
 [-1.2419674   0.22486013  1.037925  ]
 [ 1.9539233   1.1511805   0.37796873]
 [-1.1802232  -0.5915488  -0.25193694]
 [ 1.0492184  -0.13860983 -1.2118939 ]
 [ 0.5686778  -0.61162436  1.387702  ]]


In [11]:
x=tf.placeholder(tf.float32,shape=[None,3])
linear_model = tf.layers.Dense(units=1)
y = linear_model(x)

In [12]:
init = tf.global_variables_initializer()
sess.run(init)

In [13]:
print(sess.run(y,{x: [[1,2,3],[4,5,6]]}))

[[-3.2330718]
 [-8.967957 ]]


In [14]:
writer = tf.summary.FileWriter('./0')
writer.add_graph(tf.get_default_graph())